- name: Write configuration file
  shell : echo '{{apt_proxy_sock_conf}}' > /home/{{user_name}}/apt.conf
  
- name: Copy configuration
  shell: sudo cp /home/{{user_name}}/apt.conf /etc/apt/apt.conf

- name: apt-get update
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes